name: ctelnet
description: A simple Telnet client for Dart/Flutter, parse incoming and outgoing data easily and quickly.
version: 0.3.0
repository: https://github.com/chenasraf/ctelnet_dart

environment:
  sdk: ^3.1.2

dependencies:
  terminal_color_parser: any
  # terminal_color_parser:
  #   path: ../terminal_color_parser

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
