name: ctelnet
description: Telnet client for Dart/Flutter
version: 0.1.0
repository: https://github.com/chenastaf/ctelnet_dart

environment:
  sdk: ^3.1.2

# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
